# Localhost Docker Compose fil for 2. semester på datamatiker uddannelsen i Lyngby 
# Opretter to containere: 
# db2sem: Postgresql data base server som kører på port 5432
# pgadmin2sem: Webbaseret interface til brug af Postgres. Den tilgås på port 8080

version: '3.9'

services:

  db:
    #image: arm64v8/postgres:16.2 # Apple Silicon m1/m2 cpu'er
    image: postgres:16.3  # Windows og apple Intel processorer
    container_name: db_2sem
    mem_limit: 1536MB
    mem_reservation: 1024MB
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    # https://turreta.com/blog/2020/07/31/docker-compose-yml-for-pgadmin-and-postgresql/
    image: dpage/pgadmin4:8.3
    container_name: pgadmin_2sem
    mem_reservation: 512MB
    mem_limit: 1024MB
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/pgadmin
    ports:
      - "8080:80"
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cphbusiness.dk
      PGADMIN_DEFAULT_PASSWORD: 1234

networks:
  backend:
    name: backend
    internal: false # in production, it should be true if you don't want to expose this network to the outside world
    driver: bridge
